[package]
name = "hedera"
publish = false
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
hedera = { git = "https://github.com/hashgraph/hedera-sdk-rust", rev = "8970a37f1a0ea307aaa2295d3b50056ebe7c12cd" }
mbox = { version = "0.5.0" }
libc = { version = "0.2.44" }
slotmap = { version = "0.3.0", features = [ "unstable" ] }
once_cell = "0.1.6"
failure = "0.1.3"
parking_lot = { version = "0.7.0", features = [ "nightly" ] }
chrono = "0.4.6"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
