[package]
name = "hedera"
publish = false
version = "0.0.0"
edition = "2018"
authors = [
    "Ryan Leckey <ryan@launchbadge.com>"
]

[lib]
crate-type = ["staticlib"]

[dependencies]
hedera = { git = "https://github.com/hashgraph/hedera-sdk-rust", rev = "2841edec513b65caeed02363ef67a31b62b11459" }
mbox = { version = "0.5.0" }
libc = { version = "0.2.44" }
slotmap = { version = "0.3.0", features = [ "unstable" ] }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
